import { useEffect, useRef, useState } from "react"

interface UseWebRTCProps{
    socket:any;
    currentUser:any;
    otherUser:any;
}

export const useWebRTC = ({socket,currentUser,otherUser}:UseWebRTCProps) => {
    const peerConnection = useRef<RTCPeerConnection | null>(null);
    const localStream = useRef<MediaStream | null>(null);
    const [remoteStream,setRemoteStream] = useState<MediaStream|null>(null);
    const pendingCandidates = useRef<RTCIceCandidateInit[]>([]);
    const [incomingCall, setIncomingCall] = useState<any>(null);
    const [calling, setCalling] = useState(false);
    const [callAccepted, setCallAccepted] = useState(false);

    useEffect(()=>{
        const handleIncomingCall = (data:any) => {
          setIncomingCall(data);
        };
        socket.on("incoming-call", handleIncomingCall);
        return ()=>{
          socket.off("incoming-call", handleIncomingCall);
        };
    },[]);

    useEffect(()=>{
            socket.on("call-accepted",async()=>{
                setCallAccepted(true);
                setCalling(true);
                const offer = await createOffer();
                socket.emit("webrtc-offer",{
                  targetUserId:otherUser._id,
                  offer
                });
            });
            socket.on("call-rejected",()=>{
                cleanup();
                setCalling(false);
                setCallAccepted(false);
                setIncomingCall(null);
            });
            socket.on("call-ended",()=>{
                cleanup();
                setCalling(false);
                setCallAccepted(false);
                setIncomingCall(null);
            });
            socket.on("webrtc-offer",async({offer})=>{
                console.log("Offer Received");
              //Now the receiver also sends ICE candidates back.
              createPeerConnection((candidate) => {
                socket.emit("ice-candidate", {
                  targetUserId: incomingCall?.caller._id,
                  candidate,
                });
              });
              await getLocalStream();
              addLocalTracks();
              const answer = await createAnswer(offer);
              socket.emit("webrtc-answer",{
                targetUserId:incomingCall?.caller._id, answer
              });
            });
            socket.on("webrtc-answer",async({answer})=>{
                console.log("answer receive");
              await setRemoteAnswer(answer);
            })
            socket.on("ice-candidate", async ({ candidate }) => {
              await addIceCandidate(candidate);
            });
            return () => {
                socket.off("call-accepted");
                socket.off("call-rejected");
                socket.off("call-ended");
                socket.off("webrtc-offer");
                socket.off("webrtc-answer");
                socket.off("ice-candidate");
            };
    },[otherUser,socket,incomingCall]);
    
    //functions for start,end,reject,accept call
    const endCall = ()=>{
        if(!otherUser) return;
        cleanup();
        socket.emit("end-call",{
            receiverId:otherUser._id,
        });
        setCalling(false);
        setCallAccepted(false);
    };
    const startCall = async() => {
        if(!otherUser) return;
        createPeerConnection((candidate) => {
            //Now every ICE candidate generated by the caller is sent to the receiver.
                socket.emit("ice-candidate", {
                    targetUserId: otherUser._id,
                    candidate,
                });
            });
        await getLocalStream();
        addLocalTracks();
            socket.emit("call-user",{
                receiverId:otherUser._id,
                caller:currentUser,
            });
        setCalling(true);
        setCallAccepted(false);
    }
    const acceptCall = async () => {
        if(!incomingCall) return;
        socket.emit("accept-call",{
            callerId:incomingCall.caller._id
        });  
        setCalling(true);   
        setCallAccepted(true);
    }
    const rejectCall = () => {
        if(!incomingCall) return;
        socket.emit("reject-call", {
            callerId: incomingCall.caller._id
        });
        cleanup();
        setIncomingCall(null);
        setCalling(false);
        setCallAccepted(false);
    };
    //make google stun connection stun:stun.l.google.com:19302 with WebRTC
    const createPeerConnection = (onIceCandidate?: (candidate: RTCIceCandidate) => void) => {
        if(peerConnection.current){
            return peerConnection.current;
        }
        //peer connection
        peerConnection.current = new RTCPeerConnection({
            iceServers: [
            {
                urls: [
                    "stun:global.stun.twilio.com:3478",
                ],
            },
            {
                urls: [
                    "turn:global.relay.metered.ca:80",
                    "turn:global.relay.metered.ca:80?transport=tcp",
                    "turn:global.relay.metered.ca:443",
                    "turns:global.relay.metered.ca:443?transport=tcp",
                ],
                username: "...",
                credential: "...",
            },
        ]
        });
        //ICE candidate(for finding best possible routes among own hotspot, internet, wifi,friends-wifi,friends-net etc);
        peerConnection.current.onicecandidate = (event) => {
            if(event.candidate && onIceCandidate){
                onIceCandidate(event.candidate);
            }
            console.log("ICE",event.candidate);
        };
        peerConnection.current.ontrack = (event) => {
            console.log("Remote track received");
            setRemoteStream(event.streams[0]);
        };
        return peerConnection.current;
    }
    //get localStream ,asks for allow voice then start calling
    const getLocalStream = async() => {
        const stream = await navigator.mediaDevices.getUserMedia({
            audio:{
                echoCancellation:true,
                noiseSuppression:true,
                autoGainControl:true
            },
            video:false,
        });
        localStream.current = stream;
        return stream;
    }
    //add microphone for talking
    const addLocalTracks = () => {
        if (!peerConnection.current || !localStream.current) return;
        localStream.current.getTracks().forEach(track => {
            peerConnection.current?.addTrack(track,localStream.current!);
        });
    };
    peerConnection.current?.getSenders().forEach(sender => {
        if (sender.track?.kind === "audio") {
            const params = sender.getParameters();
            if (!params.encodings) {
                params.encodings = [{}];
            }
            params.encodings[0].maxBitrate = 64000;
            sender.setParameters(params);
        }
    });
    //it is used for connect via IP adress from browser a to b. details of browser like ip,supports are called offer
    const createOffer = async() => {
        if(!peerConnection.current) return null;
        const offer = await peerConnection.current.createOffer();
        await peerConnection.current.setLocalDescription(offer);
        console.log("Offer Created");
        return offer;
    }
    //make answer 
    const createAnswer = async(offer:RTCSessionDescriptionInit) => {
        if(!peerConnection.current) return null;
        await peerConnection.current.setRemoteDescription(new RTCSessionDescription(offer));
        const answer = await peerConnection.current.createAnswer();
        await peerConnection.current.setLocalDescription(answer);
        for (const candidate of pendingCandidates.current) {
            await peerConnection.current.addIceCandidate(
                new RTCIceCandidate(candidate)
            );
            console.log("Offer Remote Description Set");
        }
        pendingCandidates.current = [];
        console.log("Answer Created");
        return answer;
    }
    //set answer
    const setRemoteAnswer = async(answer:RTCSessionDescriptionInit) => {
        if(!peerConnection.current) return;
        await peerConnection.current.setRemoteDescription(new RTCSessionDescription(answer));
        for (const candidate of pendingCandidates.current) {
            await peerConnection.current.addIceCandidate(
                new RTCIceCandidate(candidate)
            );
            console.log("Remote description set");
        }
        pendingCandidates.current = [];
    }
    //make ice candidate to receive
    const addIceCandidate = async (candidate: RTCIceCandidateInit) => {
        if (!peerConnection.current) return;
        if (peerConnection.current.remoteDescription) {
            await peerConnection.current.addIceCandidate(new RTCIceCandidate(candidate));
        } else {
            pendingCandidates.current.push(candidate);
        }
    };
    //cleanup after end call
    const cleanup = async() => {
        localStream.current?.getTracks().forEach(track=>{
            track.stop();
        })
        peerConnection.current?.close();
        peerConnection.current = null;
        localStream.current = null;
        setRemoteStream(null);
        pendingCandidates.current = [];
    }

    return {
        endCall,startCall,remoteStream,incomingCall,
        acceptCall,rejectCall,callAccepted,calling
    };
}